### ISSUE TITLE
Additional faculty

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Spanish#1]
Hey @tu-chill can we use our graduate student accordion component to put at the bottom of the faculty page for their adjunct and graduate TA lists? Figure this will look way cleaner in the accordions with these long ass lists, as opposed to using the affiliated include. The have three frigging pages of faculty, it's ridiculous... 

http://www.cla.temple.edu/spanpor/faculty/adjunct-faculty/ 
http://www.cla.temple.edu/spanpor/faculty/graduate-teaching-assistants/

**Comment by tu-chill** [comment]
I do want to find a way to display this content. long lists are long. I don't think the accordion pattern is the best user interface. Am I going to look at tabs? but in the meantime, a long list will have to do.

**Comment by tu-chill** [comment]
related to https://github.com/TULiberalArts/TUtheme/issues/40
